@echo off
echo College AI Assistant - QR Code Fix
echo ================================
echo.

echo This script will help you connect your phone with a QR code
echo even when your phone and computer are on different networks.
echo.

echo Step 1: Stopping any running Metro processes...
taskkill /f /im node.exe 2>nul

echo.
echo Step 2: Clearing caches...
rd /s /q "%APPDATA%\Expo" 2>nul
rd /s /q "%USERPROFILE%\.expo" 2>nul
rd /s /q ".expo" 2>nul
rd /s /q "node_modules\.cache" 2>nul

echo.
echo Step 3: Setting up environment for stable connection...
set NODE_OPTIONS=--max-old-space-size=4096
set UV_THREADPOOL_SIZE=16
set EXPO_TUNNEL_VERBOSE=true

echo.
echo Step 4: Modifying metro.config.js to increase timeouts...
echo // Auto-generated by qr-fix.bat > metro.config.js.new
echo const { getDefaultConfig } = require('@expo/metro-config'); >> metro.config.js.new
echo. >> metro.config.js.new
echo const defaultConfig = getDefaultConfig(__dirname); >> metro.config.js.new
echo. >> metro.config.js.new
echo // Fix for Windows timing issues >> metro.config.js.new
echo defaultConfig.resolver.sourceExts.push('cjs'); >> metro.config.js.new
echo defaultConfig.transformer.assetPlugins = ['expo-asset/tools/hashAssetFiles']; >> metro.config.js.new
echo defaultConfig.server = defaultConfig.server || {}; >> metro.config.js.new
echo defaultConfig.server.timeoutInterval = 60000; >> metro.config.js.new
echo. >> metro.config.js.new
echo // Fix for tunnel mode >> metro.config.js.new
echo defaultConfig.watcher = { >> metro.config.js.new
echo   additionalExts: ['mjs', 'cjs'], >> metro.config.js.new
echo   healthCheck: { >> metro.config.js.new
echo     enabled: false, >> metro.config.js.new
echo   }, >> metro.config.js.new
echo   watchman: { >> metro.config.js.new
echo     deferStates: ['hg.update'], >> metro.config.js.new
echo   }, >> metro.config.js.new
echo }; >> metro.config.js.new
echo. >> metro.config.js.new
echo module.exports = defaultConfig; >> metro.config.js.new

move /y metro.config.js.new metro.config.js

echo.
echo Step 5: Starting Expo with tunnel mode...
echo.
echo Please wait while the QR code is being generated...
echo This may take up to 60 seconds.
echo.
echo When the QR code appears, scan it with your phone's camera.
echo.

npx expo start --tunnel

echo.
echo If the QR code doesn't appear or scanning fails, try:
echo 1. Restart your computer
echo 2. Run this script again
echo 3. Try connecting with Expo Go's "Enter URL manually" option
echo.
pause
