@echo off
echo College AI Assistant - Restore Working State
echo =========================================
echo.

echo This script will restore your project to a working state by clearing caches
echo without deleting any important files.
echo.

echo Step 1: Stopping any running Metro processes...
taskkill /f /im node.exe 2>nul

echo.
echo Step 2: Clearing Expo and Metro caches...
echo Clearing Expo cache...
rd /s /q "%APPDATA%\Expo" 2>nul
rd /s /q "%USERPROFILE%\.expo" 2>nul
rd /s /q ".expo" 2>nul
rd /s /q ".expo-shared" 2>nul
rd /s /q "node_modules\.cache" 2>nul

echo.
echo Step 3: Restoring original metro.config.js...
echo // Auto-generated by restore-working-state.bat > metro.config.js
echo const { getDefaultConfig } = require('@expo/metro-config'); >> metro.config.js
echo. >> metro.config.js
echo const defaultConfig = getDefaultConfig(__dirname); >> metro.config.js
echo. >> metro.config.js
echo defaultConfig.resolver.sourceExts.push('cjs'); >> metro.config.js
echo defaultConfig.transformer.assetPlugins = ['expo-asset/tools/hashAssetFiles']; >> metro.config.js
echo. >> metro.config.js
echo module.exports = defaultConfig; >> metro.config.js

echo.
echo Step 4: Setting environment variables for stability...
set NODE_OPTIONS=--max-old-space-size=4096
set UV_THREADPOOL_SIZE=16

echo.
echo Step 5: Starting Expo in tunnel mode...
echo.
echo Please wait while the QR code is being generated...
echo.
echo When the QR code appears, scan it with your phone's camera.
echo If the app crashes with a timing error, press Ctrl+C and run:
echo npx expo start --tunnel --no-dev
echo.

npx expo start --tunnel

echo.
echo If you encountered a timing error, try running:
echo npx expo start --tunnel --no-dev
echo.
pause
